# Generated by Django 4.1.7 on 2023-04-29 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collageName', models.TextField(max_length=100)),
                ('collageAddress', models.TextField(max_length=300)),
                ('collageDescription', models.TextField(max_length=550)),
                ('collageImage', models.ImageField(upload_to='collage/')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=200)),
                ('semester', models.IntegerField()),
                ('collageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.collage')),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designationName', models.TextField(max_length=30, unique=True)),
                ('power', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='grievanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.TextField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.TextField(max_length=17)),
                ('image', models.ImageField(upload_to='users/')),
                ('userName', models.TextField(max_length=20)),
                ('surName', models.TextField(max_length=20)),
                ('fatherName', models.TextField(max_length=20)),
                ('semester', models.IntegerField(null=True)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('Collage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.collage')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.designation')),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.TextField(max_length=17)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.designation')),
            ],
        ),
        migrations.CreateModel(
            name='complainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complainCode', models.TextField(max_length=15)),
                ('image', models.ImageField(null=True, upload_to='GrievanceImages/')),
                ('description', models.TextField(max_length=1000)),
                ('remark', models.TextField(max_length=1000, null=True)),
                ('grievanceDate', models.DateField(auto_now_add=True)),
                ('solvingDate', models.DateField(null=True)),
                ('status', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.grievancetype')),
                ('nameOfComplainant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nameOfComplainant', to='main.registration')),
                ('nameOfSolver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nameOfSolver', to='main.registration')),
            ],
        ),
    ]
