# Generated by Django 4.1.7 on 2023-04-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='enrollment',
            new_name='uniqueId',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='enrollment',
            new_name='uniqueId',
        ),
    ]
