# Generated by Django 4.1.7 on 2023-04-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_enrollment_registration_uniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaindata',
            name='complainCode',
            field=models.TextField(max_length=20),
        ),
    ]
