# Generated by Django 4.1 on 2023-05-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_collage_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaindata',
            name='feedback',
            field=models.TextField(default='Not Given Yet', max_length=100),
        ),
    ]
