# Generated by Django 4.1 on 2023-05-01 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_complaindata_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='designation',
            new_name='Designation',
        ),
    ]
