# Generated by Django 4.1 on 2023-05-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_designation_user_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Designation',
            new_name='designation',
        ),
    ]
