# Generated by Django 4.1 on 2023-05-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_complaindata_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaindata',
            name='solvingDate',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
