# Generated by Django 4.1 on 2023-05-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_complaindata_solvingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='collage',
            name='collageCity',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
