# Generated by Django 4.1 on 2023-05-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_collage_collagecity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaindata',
            name='to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
