# Generated by Django 4.1 on 2023-05-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_complaindata_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='collage',
            new_name='Manage_collage',
        ),
        migrations.RenameModel(
            old_name='complainData',
            new_name='Manage_complainData',
        ),
        migrations.RenameModel(
            old_name='department',
            new_name='Manage_department',
        ),
        migrations.RenameModel(
            old_name='designation',
            new_name='Manage_designation',
        ),
        migrations.RenameModel(
            old_name='grievanceType',
            new_name='Manage_grievanceType',
        ),
        migrations.RenameModel(
            old_name='registration',
            new_name='Manage_registration',
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='Manage_user',
        ),
    ]
