# Generated by Django 4.1 on 2023-05-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_collage_manage_collage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_collage',
            name='collageCity',
        ),
    ]
