# Generated by Django 4.1 on 2023-05-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_manage_collage_collagecity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_designation',
            name='designationName',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='manage_designation',
            name='power',
            field=models.IntegerField(),
        ),
    ]
